version: 0.2
stages:
  - build
  - publish

before_script:
  - export BRANCH_NAME=${BRANCH_NAME:-master}
  

build:
  image: docker
  stage: build
  services:
    - docker:dind
  script:
    - apk add git
    - git clone https://github.com/meetecho/janus-gateway.git --branch $BRANCH_NAME
    - cd janus-gateway
    - docker build -f ../Dockerfile -t myimage1 .
    - docker save myimage1 > ../image.tar
  artifacts:
    expire_in: 2w
    paths:
      - image.tar
  tags:
    - docker
post_build:
    commands:
      - printf '[{"name":"your.task.definition.name","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json

artifacts:
    files: imagedefinitions.json
