version: 0.2
stages:
  - build
  
before_script:
  - export BRANCH_NAME=${BRANCH_NAME:-master}
  
build:
  image: docker
  stage: build
  services:
    - docker:dind
  script:
    - apk add git
    - git clone https://github.com/meetecho/janus-gateway.git --branch $BRANCH_NAME
    - cd janus-gateway
    - docker build -f ../Dockerfile -t myimage1 .
    - docker save myimage1 > ../image.tar
  artifacts:
    expire_in: 2w
    paths:
      - image.tar
  tags:
    - docker
